id: P45BF55D4
initial_creation_type: ocr
source_metadata:
  volumes:
    4540846f66e74e39abde63a8e170cd00:
      base_file: v064.txt
      image_group_id: I1PD95909
      title: མདོ་སྡེའི་དོན་ཀུན་ལས་བཏུས་པའི་མན་ངག།
      total_pages: 1902
      volume_number: 64
